version: '3'
services:
  surveydb:
    image: "postgres:latest" # use latest official postgres version
    environment:
            POSTGRES_PASSWORD: docker
            POSTGRES_USER: postgres
            POSTGRES_DB: survey
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
  mobile:
    container_name: survey-api
    restart: always
    build: .
    ports:
      - "3435:3435"
    depends_on:
      - surveydb
volumes:
  database-data: # named volumes can be managed easier using docker-compose

